### ISSUE TITLE
1.0.0 release checklist

### ISSUE THREAD

**Issue by wch** [r-lib/fastmap#11]
Before submitting to CRAN:
- [x] Bump version to 1.0.0
- [x] Check with win-builder
- [x] Pass `R CMD check --as-cran`
- [x] Submit

After accepted on CRAN:
- [x] Tag version
- [x] Rebuild website
